# ==============================
# Server configuration
# ==============================
server:
  port: 8089
  address: 0.0.0.0   # allow access from other PCs in network

# ==============================
# Spring application
# ==============================
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://config-server:8888"

  cloud:
    gateway:
      server:
        webflux:

          # ==============================
          # Service discovery (Eureka)
          # ==============================
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          # ==============================
          # API Routes configuration
          # ==============================
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1

            - id: auth-route
              uri: lb://user-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/courses/**
              filters:
                - StripPrefix=1

            - id: activity-service
              uri: lb://activity-service
              predicates:
                - Path=/activities/**
              filters:
                - StripPrefix=1

            - id: analytics-service
              uri: lb://analytics-service
              predicates:
                - Path=/analytics/**
              filters:
                - StripPrefix=1

# ==============================
# Swagger aggregation for Gateway
# ==============================
springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /users/v3/api-docs
      - name: Course Service
        url: /courses/v3/api-docs
      - name: Activity Service
        url: /activities/v3/api-docs
      - name: Analytics Service
        url: /analytics/v3/api-docs
