server:
  port: 3334

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://spring-config:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
